#pragma once
#ifndef CONG_BOOLEAN_LANG_CORE_BOOLEANLEXICAL_HH
#define CONG_BOOLEAN_LANG_CORE_BOOLEANLEXICAL_HH

// @todo rather provide as function macro (thunk)?
#define CONG_LANG_CORE_FALSE 0
#define CONG_LANG_CORE_TRUE  1

// @todo provide other boolean operations

// @todo not optimal, improve (rename RES_?)
#define CONG_LANG_CORE_LOCAL_COND_0(RES_TRUE_PAREN,RES_FALSE_PAREN)\
CONG_LANG_CORE_INTERN_UNPAREN(RES_FALSE_PAREN)

#define CONG_LANG_CORE_LOCAL_COND_1(RES_TRUE_PAREN,RES_FALSE_PAREN)\
CONG_LANG_CORE_INTERN_UNPAREN(RES_TRUE_PAREN)

#define CONG_LANG_CORE_LOCAL_COND(COND_,RES_TRUE_PAREN,RES_FALSE_PAREN)\
CONG_LANG_CORE_INTERN_PASTE(CONG_LANG_CORE_LOCAL_COND_,COND_)(RES_TRUE_PAREN,RES_FALSE_PAREN)

#define CONG_LANG_CORE_COND(COND_,RES_TRUE_PAREN,RES_FALSE_PAREN)\
CONG_LANG_CORE_LOCAL_COND(CONG_LANG_CORE_INTERN_EVAL(COND_),RES_TRUE_PAREN,RES_FALSE_PAREN)
#endif
