#pragma once
#ifndef CONG_NUMBER_LANG_CORE_NATURALLEXICAL_HH
#define CONG_NUMBER_LANG_CORE_NATURALLEXICAL_HH

// @todo extend to larger numbers / use boost preprocessor lib
#define CONG_LANG_CORE_LOCAL_SUCC_DISPATCH_0 1
#define CONG_LANG_CORE_LOCAL_SUCC_DISPATCH_1 2
#define CONG_LANG_CORE_LOCAL_SUCC_DISPATCH_2 3
#define CONG_LANG_CORE_LOCAL_SUCC_DISPATCH_3 4
#define CONG_LANG_CORE_LOCAL_SUCC_DISPATCH_4 5
#define CONG_LANG_CORE_LOCAL_SUCC_DISPATCH_5 6
#define CONG_LANG_CORE_LOCAL_SUCC_DISPATCH_6 7
#define CONG_LANG_CORE_LOCAL_SUCC_DISPATCH_7 8
#define CONG_LANG_CORE_LOCAL_SUCC_DISPATCH_8 9
#define CONG_LANG_CORE_LOCAL_SUCC_DISPATCH_9 10
#define CONG_LANG_CORE_SUCC(N_)\
CONG_LANG_CORE_INTERN_PASTE(CONG_LANG_CORE_LOCAL_SUCC_DISPATCH_,N_)

// @todo pred and other operations needed? (if so, consider using boost preprocessor lib)

#endif
